config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "ejemplo#index"
  get "/primera/pagina/rails", to: "ejemplo#index"
  get '/comodin/:x', to: 'ejemplo#index'
  # get '/primera/pagina/rails', action: :index, controller: 'ejemplo'
  get "pagina/inicio", to: "ejemplopro#index"
  get "pagina/contacto", to: "ejemplopro#contacto"
  get "pagina/otro", to: "ejemplopro#otro" 
  get "producto", to: "ejemplo#producto"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ejemplo_controller.rb
class EjemploController < ApplicationController

    def index 

    end

    def producto 

    end


end

app/controllers/ejemplopro_controller.rb
class EjemploproController < ApplicationController
  def index
  end

  def contacto
  end

  def otro
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ejemplo_helper.rb
module EjemploHelper
end

app/helpers/ejemplopro_helper.rb
module EjemploproHelper
end

app/views/ejemplo/index.html.erb
<h1>HOLA soy una vista del controlador ejemplo</h1>

app/views/ejemplo/producto.html.erb
<h1>Soy la vista producto</h1>

app/views/ejemplopro/contacto.html.erb
<h1>Ejemplopro#contacto</h1>
<p>Find me in app/views/ejemplopro/contacto.html.erb</p>

app/views/ejemplopro/index.html.erb
<h1>Ejemplopro#index</h1>
<p>Find me in app/views/ejemplopro/index.html.erb</p>
<a href="https://www.google.cl">Ir a Google</a>

<%= Time.now.year %>

<%  edad = 25
    if edad >= 18 %>
    <h1>Eres mayor de edad</h1>
<% else %>
    <h1>Eres menor de edad</h1>
<% end %>

app/views/ejemplopro/otro.html.erb
<h1>Ejemplopro#otro</h1>
<p>Find me in app/views/ejemplopro/otro.html.erb</p>
<%= pagina_otro_path %>
<br>
<%= pagina_otro_url %>
<br>
<%= link_to "ir a inicio", pagina_inicio_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projecto1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1>HOLA soy del LAYOUT Application</h1>
    <%= yield %>
    <h1>Soy un pie del LAYOUT</h1>
  </body>
</html>